# Generated by Django 6.0.4 on 2026-05-05 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0003_alter_storagelocation_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        help_text="Course code (e.g. PHYS 215)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "course_title",
                    models.CharField(help_text="Official course title", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the lab course"
                    ),
                ),
            ],
            options={
                "ordering": ["course_code"],
            },
        ),
        migrations.CreateModel(
            name="AcademicTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable term name (e.g. Fall 2026)",
                        max_length=50,
                    ),
                ),
                (
                    "term_type",
                    models.CharField(
                        choices=[
                            ("fall", "Fall"),
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                        ],
                        help_text="Determines scheduling assumptions (weekly vs condensed)",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about calendar irregularities",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
                "unique_together": {("name", "term_type")},
            },
        ),
        migrations.CreateModel(
            name="LabOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_lab_room",
                    models.CharField(
                        blank=True,
                        help_text="Primary lab room used for door postings and schedules",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Coordinator notes specific to this offering",
                    ),
                ),
                (
                    "academic_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_offerings",
                        to="scheduling.academicterm",
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        help_text="Faculty coordinator for this lab course offering",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coordinated_lab_offerings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="scheduling.labcourse",
                    ),
                ),
            ],
            options={
                "ordering": ["academic_term", "lab_course"],
                "unique_together": {("lab_course", "academic_term")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_number",
                    models.PositiveIntegerField(
                        help_text="Instructional week number (e.g. Week 1, Week 2)"
                    ),
                ),
                (
                    "week_start_date",
                    models.DateField(
                        help_text="Date of the Monday for this instructional week"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes (holiday adjustments, skipped content, etc.)",
                    ),
                ),
                (
                    "lab_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_weeks",
                        to="scheduling.laboffering",
                    ),
                ),
            ],
            options={
                "ordering": ["week_number"],
                "unique_together": {("lab_offering", "week_number")},
            },
        ),
        migrations.CreateModel(
            name="LabSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_code",
                    models.CharField(
                        help_text="Section identifier (e.g. L01, L02, A1)",
                        max_length=10,
                    ),
                ),
                (
                    "meeting_day",
                    models.CharField(
                        blank=True,
                        help_text="Day of the week this section meets (for reference only)",
                        max_length=20,
                    ),
                ),
                (
                    "meeting_time",
                    models.CharField(
                        blank=True,
                        help_text="Meeting time (for reference only)",
                        max_length=20,
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True,
                        help_text="Lab room where this section meets",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes specific to this section"
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        help_text="Graduate TA or instructor leading this section",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="scheduling.laboffering",
                    ),
                ),
            ],
            options={
                "ordering": ["section_code"],
                "unique_together": {("lab_offering", "section_code")},
            },
        ),
        migrations.CreateModel(
            name="WeekMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meeting_order",
                    models.PositiveIntegerField(
                        help_text="Order of the meeting within the week (1 = first, 2 = second)"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional label (e.g. Mon, Wed, Meeting A)",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes specific to this meeting"
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduled_meetings",
                        to="equipment.experiment",
                    ),
                ),
                (
                    "schedule_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="scheduling.scheduleweek",
                    ),
                ),
            ],
            options={
                "ordering": ["meeting_order"],
                "unique_together": {("schedule_week", "meeting_order")},
            },
        ),
    ]
