# Generated by Django 6.0.4 on 2026-05-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weekmeeting",
            name="number_of_stations",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of student stations for this meeting"
            ),
        ),
    ]
