# Generated by Django 6.0.4 on 2026-04-29 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inventory_tag",
                    models.CharField(
                        help_text="Barcode / human-readable inventory identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Canonical item name", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the item"
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Alternate names, synonyms, and search terms",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Broad category, e.g. Optics, Electronics, Mechanics",
                        max_length=100,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model_number", models.CharField(blank=True, max_length=255)),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer serial number, if present",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "asset_tag",
                    models.CharField(
                        blank=True,
                        help_text="Institutional asset or property tag",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tracking_level",
                    models.CharField(
                        choices=[
                            ("individual_serialized", "Individual (Serialized)"),
                            (
                                "individual_non_serialized",
                                "Individual (Non-Serialized)",
                            ),
                            ("bulk", "Bulk"),
                        ],
                        help_text="Defines how this item is tracked",
                        max_length=40,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of items (only >1 for bulk items)"
                    ),
                ),
                (
                    "storage_length",
                    models.FloatField(
                        blank=True, help_text="Length of item in storage", null=True
                    ),
                ),
                (
                    "storage_width",
                    models.FloatField(
                        blank=True, help_text="Width of item in storage", null=True
                    ),
                ),
                (
                    "storage_height",
                    models.FloatField(
                        blank=True, help_text="Height of item in storage", null=True
                    ),
                ),
                (
                    "storage_footprint_area",
                    models.FloatField(blank=True, editable=False, null=True),
                ),
                (
                    "storage_volume",
                    models.FloatField(blank=True, editable=False, null=True),
                ),
                ("setup_length", models.FloatField(blank=True, null=True)),
                ("setup_width", models.FloatField(blank=True, null=True)),
                ("setup_height", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("is_stackable", models.BooleanField(default=False)),
                (
                    "max_stack_height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of identical items that can be stacked",
                        null=True,
                    ),
                ),
                (
                    "storage_orientation",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("flat", "Flat"),
                            ("upright", "Upright"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                ("requires_heavy_duty_shelving", models.BooleanField(default=False)),
                ("requires_climate_control", models.BooleanField(default=False)),
                ("requires_dark_storage", models.BooleanField(default=False)),
                ("requires_secure_storage", models.BooleanField(default=False)),
                (
                    "hazard_class",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "access_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("checked_out", "Checked out"),
                            ("under_repair", "Under repair"),
                            ("surplus", "Surplus"),
                            ("retired", "Retired"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "handling_notes",
                    models.TextField(
                        blank=True,
                        help_text="Special handling notes or legacy comments",
                    ),
                ),
                (
                    "migration_flags",
                    models.TextField(
                        blank=True,
                        help_text="Flags created during initial data migration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        help_text="Course or lab identifier (e.g. PHY 215 Lab)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "experiment_title",
                    models.CharField(
                        help_text="Human-readable title of the experiment",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the experiment and its purpose",
                    ),
                ),
                (
                    "preferred_lab_type",
                    models.CharField(
                        blank=True,
                        help_text="Preferred lab type (optics, electronics, general, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "requires_fixed_installation",
                    models.BooleanField(
                        default=False,
                        help_text="True if experiment requires permanent or semi-permanent installation",
                    ),
                ),
                (
                    "move_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="True if experiment is sensitive to move timing or disruption",
                    ),
                ),
                (
                    "setup_space_required",
                    models.FloatField(
                        blank=True,
                        help_text="Approximate floor area required when the experiment is set up",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["course_code"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_access_id",
                    models.PositiveIntegerField(
                        help_text="Primary key of the original Access database row",
                        unique=True,
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        help_text="Vendor or supplier name", max_length=255
                    ),
                ),
                (
                    "fiscal_year",
                    models.PositiveIntegerField(
                        help_text="Fiscal year charged for this purchase"
                    ),
                ),
                (
                    "date_ordered",
                    models.DateField(
                        blank=True, help_text="Date the item(s) were ordered", null=True
                    ),
                ),
                (
                    "date_received",
                    models.DateField(
                        blank=True,
                        help_text="Date the item(s) were received",
                        null=True,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True, help_text="Vendor order number", max_length=255
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        blank=True,
                        help_text="Purchase order number (if applicable)",
                        max_length=255,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Credit card, contract vendor, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "item_unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Unit cost of one item",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Shipping cost for the purchase",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tax charged on the purchase",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Discount applied to the purchase",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "extended_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total extended cost for the purchase",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "backorder_flag",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether any items were backordered",
                    ),
                ),
                (
                    "backorder_quantity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of items on backorder", null=True
                    ),
                ),
                (
                    "backorder_received_date",
                    models.DateField(
                        blank=True,
                        help_text="Date backordered items were received",
                        null=True,
                    ),
                ),
                (
                    "purchase_relevance_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes regarding relevance for move or replacement decisions",
                    ),
                ),
                (
                    "replacement_priority",
                    models.CharField(
                        blank=True,
                        help_text="Low / Medium / High replacement priority",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General notes or legacy comments"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True,
                        help_text="Building identifier (if known)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        help_text="Room number or room identifier", max_length=100
                    ),
                ),
                (
                    "cabinet",
                    models.CharField(
                        blank=True,
                        help_text="Cabinet identifier (if applicable)",
                        max_length=100,
                    ),
                ),
                (
                    "shelf",
                    models.CharField(
                        blank=True,
                        help_text="Shelf or sub-location within cabinet",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Uploaded image file", upload_to="equipment_images/"
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("condition", "Condition"),
                            ("storage", "Storage"),
                            ("setup", "Setup"),
                            ("move", "Move-related"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Category describing what the image represents",
                        max_length=20,
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        help_text="Optional caption or description of the image",
                    ),
                ),
                (
                    "date_taken",
                    models.DateField(
                        blank=True,
                        help_text="Date the photo was taken (if known)",
                        null=True,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="equipment.equipmentitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Name of the field that was changed", max_length=100
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, help_text="Previous value of the field"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, help_text="New value of the field"),
                ),
                (
                    "changed_by",
                    models.CharField(
                        help_text="User or system that made the change", max_length=255
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        help_text="Reason for the change (migration, review, move, correction, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "related_move_phase",
                    models.CharField(
                        blank=True,
                        help_text="Pre-move, in-transit, or post-move (if applicable)",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="equipment.equipmentitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="equipmentitem",
            name="purchase_record",
            field=models.ForeignKey(
                help_text="Purchase record associated with this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipment_items",
                to="equipment.purchaserecord",
            ),
        ),
        migrations.CreateModel(
            name="RepairLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_reported",
                    models.DateField(
                        help_text="Date the issue was reported or observed"
                    ),
                ),
                (
                    "issue_description",
                    models.TextField(help_text="Description of the problem or damage"),
                ),
                (
                    "repair_action",
                    models.TextField(
                        blank=True, help_text="Description of repair action taken"
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(
                        blank=True,
                        help_text="Person or service that performed the repair",
                        max_length=255,
                    ),
                ),
                (
                    "repair_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost of repair (if applicable)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True,
                        help_text="Outcome of the repair (successful, temporary fix, not repairable, etc.)",
                    ),
                ),
                (
                    "move_related",
                    models.BooleanField(
                        default=False,
                        help_text="True if the issue was caused by or discovered during a move",
                    ),
                ),
                (
                    "pre_move_condition_documented",
                    models.BooleanField(
                        default=False,
                        help_text="True if condition was documented prior to the move",
                    ),
                ),
                (
                    "post_move_condition_documented",
                    models.BooleanField(
                        default=False,
                        help_text="True if condition was documented after the move",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repair_logs",
                        to="equipment.equipmentitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_reported", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="equipmentitem",
            name="current_location",
            field=models.ForeignKey(
                help_text="Current physical storage location",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipment_items",
                to="equipment.storagelocation",
            ),
        ),
        migrations.CreateModel(
            name="EquipmentExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_used",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of units of this item used in the experiment",
                    ),
                ),
                (
                    "is_core_to_experiment",
                    models.BooleanField(
                        help_text="True if this equipment is essential to the experiment",
                        null=True,
                    ),
                ),
                (
                    "temporary_substitution_allowed",
                    models.BooleanField(
                        help_text="Indicates whether a temporary substitute could be used",
                        null=True,
                    ),
                ),
                (
                    "storage_group_label",
                    models.CharField(
                        blank=True,
                        help_text="Label for grouping related equipment during storage or moves",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about usage or legacy information",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiment_links",
                        to="equipment.equipmentitem",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_links",
                        to="equipment.experiment",
                    ),
                ),
            ],
            options={
                "unique_together": {("equipment", "experiment")},
            },
        ),
    ]
