# Generated by Django 6.0.4 on 2026-04-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserecord",
            name="legacy_access_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Primary key of the original Access database row (migration only)",
                null=True,
                unique=True,
            ),
        ),
    ]
