# Generated by Django 6.0.4 on 2026-04-29 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_alter_purchaserecord_legacy_access_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storagelocation",
            options={"ordering": ["building", "room", "cabinet", "shelf"]},
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="floor_area_allocated",
            field=models.FloatField(
                blank=True,
                help_text="Square footage allocated to this location",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="is_final_location",
            field=models.BooleanField(
                default=False,
                help_text="True if this is the intended final storage location",
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="location_notes",
            field=models.TextField(
                blank=True, help_text="Freeform notes about this location"
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("current", "Current"),
                    ("temporary", "Temporary"),
                    ("future", "Future"),
                ],
                default="current",
                help_text="Indicates whether this is a current, temporary, or future location",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="volume_capacity",
            field=models.FloatField(
                blank=True,
                help_text="Total volume capacity of this location",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="weight_capacity",
            field=models.FloatField(
                blank=True,
                help_text="Maximum supported weight for this location",
                null=True,
            ),
        ),
    ]
