# Generated by Django 6.0.4 on 2026-05-05 19:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0003_alter_storagelocation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentitem",
            name="storage_height_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Storage Height (m)",
            ),
        ),
        migrations.AddField(
            model_name="equipmentitem",
            name="storage_length_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Internal storage length in meters",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Storage Length (m)",
            ),
        ),
        migrations.AddField(
            model_name="equipmentitem",
            name="storage_width_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Storage Width (m)",
            ),
        ),
    ]
