# Generated by Django 6.0.4 on 2026-05-05 21:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0005_experiment_required_height_m_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagelocation",
            name="usable_height_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Clear usable height in meters",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Usable Height (m)",
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="usable_length_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Usable length of the lab space in meters",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Usable Length (m)",
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="usable_width_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Usable Width (m)",
            ),
        ),
    ]
