# Generated by Django 6.0.4 on 2026-05-08 19:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0006_storagelocation_usable_height_m_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model_number", models.CharField(blank=True, max_length=255)),
                (
                    "storage_length_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "storage_width_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "storage_height_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="equipmentitem",
            name="storage_height_m",
        ),
        migrations.RemoveField(
            model_name="equipmentitem",
            name="storage_length_m",
        ),
        migrations.RemoveField(
            model_name="equipmentitem",
            name="storage_width_m",
        ),
        migrations.RemoveField(
            model_name="experiment",
            name="description",
        ),
        migrations.RemoveField(
            model_name="experiment",
            name="required_height_m",
        ),
        migrations.RemoveField(
            model_name="experiment",
            name="required_length_m",
        ),
        migrations.RemoveField(
            model_name="experiment",
            name="required_width_m",
        ),
        migrations.RemoveField(
            model_name="experiment",
            name="setup_space_required",
        ),
        migrations.AlterField(
            model_name="experiment",
            name="course_code",
            field=models.CharField(
                help_text="Course code this experiment is typically associated with",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="experiment_title",
            field=models.CharField(
                help_text="Human-readable experiment title", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="move_sensitive",
            field=models.BooleanField(
                default=False, help_text="Experiment equipment is sensitive to movement"
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="preferred_lab_type",
            field=models.CharField(
                blank=True,
                help_text="Preferred lab environment (e.g. optics, electronics)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="experiment",
            name="requires_fixed_installation",
            field=models.BooleanField(
                default=False, help_text="Experiment requires fixed lab infrastructure"
            ),
        ),
        migrations.AddField(
            model_name="equipmentitem",
            name="equipment_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="equipment.equipmenttype",
            ),
        ),
        migrations.CreateModel(
            name="ExperimentEquipmentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_required", models.PositiveIntegerField(default=1)),
                (
                    "equipment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment.equipmenttype",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_requirements",
                        to="equipment.experiment",
                    ),
                ),
            ],
            options={
                "unique_together": {("experiment", "equipment_type")},
            },
        ),
    ]
