# Generated by Django 6.0.4 on 2026-05-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0010_alter_experiment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentitem",
            name="quantity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of physical units represented by this item (bulk only)",
                null=True,
            ),
        ),
    ]
