# Generated by Django 6.0.4 on 2026-05-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0011_equipmentitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentitem",
            name="inventory_tag",
            field=models.CharField(
                blank=True,
                help_text="Barcode / human-readable inventory identifier",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
