# Generated by Django 6.0.4 on 2026-05-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0012_alter_equipmentitem_inventory_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentitem",
            name="qr_code_image",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
