# Generated by Django 6.0.4 on 2026-05-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0014_equipmentrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipmentrequest",
            name="duration_hours",
        ),
        migrations.AddField(
            model_name="equipmentrequest",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True, help_text="When the equipment should be returned", null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipmentrequest",
            name="request_type",
            field=models.CharField(
                blank=True,
                choices=[("equipment", "Equipment"), ("experiment", "Experiment/Demo")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="equipmentrequest",
            name="start_datetime",
            field=models.DateTimeField(help_text="When the equipment is needed"),
        ),
    ]
